### ISSUE TITLE
Idea: instead of "Must have at least one snapshot to save and exit." message that forces "Dismiss", allow user to take snapshot and exit

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#147]
When trying to "save & exit" before taking any snapshots, I get a modal with the message

```
Must have at least one snapshot to save and exit.
```

And a Dismiss button. A small improvement IMO would be to allow the user to take that snapshot right away and exit, instead of requiring them to dismiss, take a snapshot, and then click on the exit button again.

Maybe the text can change to something like "You must have at least one snapshot before you can save. Would you like to take a snapshot right now?" and buttons "Take snapshot & exit" and "Dismiss"

**Comment by hadley** [comment]
I think this is a good idea, but the recorder app is relatively low priority and given the resources available for shinytest, it's unlikely to ever rise to the top of the to do list. I don't believe in saving issues "for a rainy day" so I'm closing this issue (but it's still indexed by google and we can re-open if this turns out to be a widespread request).
