### ISSUE TITLE
Error when shiny bookmarking is enabled

### ISSUE THREAD

**Issue by davesteps** [rstudio/shinytest#161]
I have a basic app with bookmarking enabled like so:

```
library(shiny)

enableBookmarking(store = 'server')

ui <- function(request){
  fluidPage(
    titlePanel("Hello Shiny!"),
    sidebarLayout(
      sidebarPanel(
        sliderInput(inputId = "bins",
                    label = "Number of bins:",
                    min = 1,max = 50,
                    value = 30),
        bookmarkButton()
      ),
      mainPanel(
        plotOutput(outputId = "distPlot")
      )
    )
  )}

server <- function(input, output) {
  output$distPlot <- renderPlot({
    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    hist(x, breaks = bins)
  })
}

shinyApp(ui = ui, server = server)

```

If I then try to record a test using `shinytest::recordTest()` I get the following error:

```
Error in session_makeRequest(self, private, endpoint, data, params, headers) : 
  Syntax error, unrecognized expression: #._bookmark_,#._bookmark_
```

**Comment by wch** [comment]
This error is fixed now. But there are some possible issues with testing apps with bookmarking:

* When you click on the bookmark button, it takes a little time for the modal to fade in, so you'll want to pause before taking a snapshot. Similarly, after dismissing the modal, it takes a little time for it to fade out.
* Clicking on the Dismiss button is not an action that shinytest records, since it does not send any information to the server -- it all happens on the client. However, you can trigger a click, as shown in the script below.
* In your example test app, the URL generated for server-side bookmarking will change every time, so if you are taking a snapshot (with screenshot) when the modal is URL visible, you will get spurious differences every time you run the test.


Here's an example test script with modifications to deal with the first two issues above.

```R
app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(bins = 18)
app$setInputs(`._bookmark_` = "click")
# Wait for modal to fade in
Sys.sleep(1)
app$snapshot()

# Click dismiss button
app$executeScript('$("#shiny-modal button[data-dismiss=\\"modal\\"]").click()');
# Wait for modal to fade out
Sys.sleep(1)

app$setInputs(bins = 20)
app$snapshot()
```

**Comment by davesteps** [comment]
Many thanks @wch thats awesome. Out of interest, could that approach for triggering the dismiss button `app$executeScript()` work for simulating clicks on htmlwidgets like leaflet?

**Comment by wch** [comment]
@davesteps I think that should work, although the Javascript code will probably be more complicated.
