### ISSUE TITLE
Snapshots not captured after the height exceeds 32768 pixels

### ISSUE THREAD

**Issue by monikav** [rstudio/shinytest#163]
I am using shiytest to test an rmarkdown with runtime shiny and I am facing a problem in capturing snapshots which has height more than 32768 pixels. The pixels after this height are completely grey and doesn't contain the original image. I am using shinytest 1.2.0.90.

**Comment by wch** [comment]
I think PhantomJS has a hard limit of 32768 for screenshots: https://github.com/ariya/phantomjs/issues/11934

It might be possible to use the workaround mentioned there -- take multiple screenshots and stitch them together -- but we probably won't have the resources to do that soon.

**Comment by hadley** [comment]
Thanks for filing this bug report! Unfortunately because it's so hard to reproduce or we think it's unlikely to affect many people, we don't have the development resources to fix at this time. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.
