### ISSUE TITLE
Unable to find input binding for element with id viz_xvar

### ISSUE THREAD

**Issue by vnijs** [rstudio/shinytest#197]
@wch It seems shinytest has some difficulties running tests for radiant.data. See message below. 
It seems that whenever I select a variable the resulting test will fail. Any suggestions on how to further diagnose the issue?

```r
Loading required package: shiny

Listening on http://127.0.0.1:7285
Saved test code to /Users/vnijs/Desktop/Github/radiant.data/inst/app/tests/mytest.R
Running mytest.R Error in session_makeRequest(self, private, endpoint, data, params, headers) : 
  Unable to find input binding for element with id viz_xvar
```
App:

https://github.com/radiant-rstats/radiant.data

Generated test script:

```r
app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(tabs_data = "Visualize")
app$setInputs(viz_xvar = c("price", "carat", "clarity"))
app$setInputs(viz_run = "click")
app$snapshot()
```

**Comment by wch** [comment]
If you put a `Sys.sleep(2)` before that line, does it work?

**Comment by vnijs** [comment]
Thanks @wch! In addition to the very nice functionality ... great looking app! Luv the diff view htmlwidget as well.

A couple questions if that is ok:

- Is wrapping possible in the diff viewer? It looks great but some of the html lines are loooonnngggg. Would also be a great htmlwidget to have stand-alone and perhaps to use with something like https://github.com/trestletech/shinyAce
- In addition to app tests, this tool seems like a great way to make a bunch of screenshots from one (large navbarPage) app to use for classes, documentation, etc. I'm basically trying to tell `shinytest` that app.R is in a particular folder, which may have lots of large data files, and then run "tests" on app.R as defined below. The tests would then take a number of screenshots using `app$takeScreenshot`. The content of my app.R below seems similar to the setup discussed in the [documentation](https://rstudio.github.io/shinytest/articles/package.html#application-objects-created-by-functions) but doesn't actually open the testing environment when I use `recordTest("tests/bca/")` and tests/bca/ is where app.R is stored. Rather I get the messages below, ending in `Error in shiny::` shown below.

```r
Error in sd_startShiny(self, private, path, seed, loadTimeout, shinyOptions) : 
  Error starting application:
Running application in test mode.
Loading required package: shiny
...
Attaching package: ‘radiant.data’
...
Error in shiny::
```

app.R

```r
library(radiant.data)
## load a state file that will automatically be pulled in when the app launches
load(url("https://github.com/radiant-rstats/docs/blob/gh-pages/examples/radiant-state.rda?raw=true"))
shiny::runApp(system.file("app", package = "radiant.data"), launch.browser = TRUE)
```

FYI When I run test in the package directory and load the state file mentioned, the testing environment doesn't pull the state information into the app as would happen if I run the app as usual. I.e., the app should open on the visualize tab based on the app state. Then click on the green button to get the plot shown below. 

![image](https://user-images.githubusercontent.com/2998956/39902480-05550c00-5483-11e8-87ba-46e6573e5d47.png)

**Comment by wch** [comment]
I'm glad that worked! I'm not glad that it was necessary, though. The goal for shinytest was to be smart about when an input change resulted in an output change, and wait for the event to happen before moving on to the next step. My guess is that there were multiple levels of dynamic UI in response to that input change.

Wrapping currently isn't possible, but adding it should be simple -- it would just need a checkbox which enabled text wrap CSS property.

The diff viewer is actually an htmlwidget. We've discussed spinning it off into a separate package, but we haven't done anything about it yet.

I'm not sure why you're having errors recording tests for your application. It appears to be stopping in the middle of a message, where it says `Error in shiny::`. I suspect this is because it's hitting the limit of a buffer used for logging. I'll try to take a look at this in the upcoming weeks.

You can actually run a test script without running `testApp()`. All you have to do is take your test script, and `source()` it. You just need to change `../` to point to the correct directory, relative to your current working dir. One nice thing is that you don't need to call `app$snapshot()` at all. For debugging, you can also step through the script at the console, and run extra commands.

```
app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(tabs_data = "Visualize")
app$takeScreenshot()
```

As for the last issue, with it not loading the state information: I'm not sure why that's happening, though it's possible it's a timing issue that could be worked around with a `Sys.sleep()` for now.

**Comment by vnijs** [comment]
I do use renderUI a lot in my apps. I can see how that would make it harder to automatically determine how long to wait. Not a big deal to add some "sleep" here and there however.

The diff viewer as a separate package sounds great!

Making some progress with building-up scripts as you suggested. One thing that would be really handy would be to set the sort order and/or filter information for a DT table. I saw how htmlwidgets are mentioned in the docs. There is no way to set something like `pivotr_rows_all` right where pivotr is the table id? I got the message below. More generally, is there a way to access/read and set things like `reactiveValues` and other settings in the app environment?

```r
Error in session_makeRequest(self, private, endpoint, data, params, headers) : 
  Unable to find input binding for element with id pivotr_rows_all
```

**Comment by wch** [comment]
> I do use renderUI a lot in my apps. I can see how that would make it harder to automatically determine how long to wait. Not a big deal to add some "sleep" here and there however.

Shinytest currently works and is tested with one level of `renderUI`. It doesn't do it based on time -- there's logic so that it waits for the right events to occur before it moves on, but your app is probably too complex for that logic to work correctly.

There currently isn't a way to set arbitrary input values, but we have an issue for it (#193). 

If you want to read arbitrary values, see https://rstudio.github.io/shinytest/articles/in-depth.html#exported-values. For writing them, there isn't a way to do that directly with shinytest. You can, however use `getOption("shiny.testmode", default = FALSE)`, and alter the behavior of your app based on that.

**Comment by thercast** [comment]
@vnijs just chiming in to say that I'm using `shinytest` for some rather complex apps at work, and for now I'd recommend adding custom code to your apps that create arbitrary inputs (such as a selectInput for the rows in a data frame rendered by a `DT::datatable()`) when the app is executed in test mode (see the updated FAQ entry [here](https://rstudio.github.io/shinytest/articles/faq.html#how-can-my-app-detect-if-its-running-in-shinytest)).  I'm planning on a longer post about this in the RStudio Community portal and/or a new episode on my podcast, as this little trick (while a bit clunky) enables me to use `shinytest` on my production apps.

**Comment by vnijs** [comment]
Thanks for the suggestions @wch. Looking forward to seeing your post @thercast !
