### ISSUE TITLE
snapshotDownload not fully leveraged

### ISSUE THREAD

**Issue by KJByron** [rstudio/shinytest#225]
first - thank you for this amazing library, it has reduced my release cycle substantially

the issue:  my shiny apps often have a download button that gives the user a pdf with a write-up of the analysis/results, currently these can't be part of the automated test/compare cycle

what happens:
testApp captures the download request by adding 
`app$snapshotDownload("report")`
to the test script
reports are captured in the expected/current folders as ###.download
of course the .download extension is not recognized
if I change the extension to .pdf the reports can be opened but viewTestDiff doesn't recognize diferences

currently I'm using shinytest to save my before and after reports, changing the extensions, and comparing them outside the system
am hoping you can bring this capability into shinytest

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think this is out of scope for shinytest since it would require the ability to compare and diff pdf files, which would be a substantially amount of work and is mostly orthogonal to the problem of testing shiny apps. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
