### ISSUE TITLE
More complex updates

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/shinytest#25]
The idea is the following: you can also specify the expected output of a widget. Sg. like

```
app$expect_update_to(xcol = "blah", clusters = 4, output = list(plot1 = corrent_plot))
```

This will basically perform the update sequence, and then wait until the output has the desired value, or a timeout kicks in.

The tricky thing is to guess when shiny is done. My initial idea:
1. listen to update events (`shiny::value`) for the output widget (`plot1` above) and then
2. wait until Shiny becomes idle. When it does, compare the output to the desired one. 
1. If they match, success.
2. If they don't wait a bit more (until the timeout?) and compare again.

**Comment by gaborcsardi** [comment]
It would be nice to have a single function for all updates, if possible. E.g.
```r
expect_update(app, ..., output = list(plot1 = correct_plot))
expect_update(app, ..., output = c("plot1"))
```
can both work. The latter only checks the update. The former checks the update, then the value.

**Comment by gaborcsardi** [comment]
Also, we could assemble a JS script to do all the updates at once. Although I am not sure if this is always a good idea.

**Comment by wch** [comment]
I think it's a good idea to at least have the ability to make the updates happen all at once. This should be fine in most cases. For it to work, I think we'll have to:

* Queue up all the updates in the JS side.
* Execute all the `setValue()` calls. This must be done with one call to a JS function. (The interpreter can't be allowed to return to the event loop between setting values; otherwise it might send values to the server between `setValue()` calls.)
* Wait for the new input values to be sent to the server. I think this should happen on the next tick of the event loop.

**Comment by gaborcsardi** [comment]
Started doing this yesterday, got stuck in https://github.com/MangoTheCat/webdriver/issues/39 whichwe had to fix, anyway.

**Comment by hadley** [comment]
Looks like this is now `expectUpdate()`
