### ISSUE TITLE
Shinytest error

### ISSUE THREAD

**Issue by muhammadarslanshabbir** [rstudio/shinytest#287]
I am testing my application in which user needs to import a template(excel) but it keeps on giving following error:

Error in session_makeRequest(self, private, endpoint, data, params, headers) : 
  SyntaxError: DOM Exception 12

**Comment by alexdaraganov** [comment]
Hi Muhammad, I believe i have the same issue.
I am trying to create a shinytest code to test my shiny application.
on my app page I have fileInput control that supposed to accept multiple .xlsx files to be imported into a database that sits behind my app page. 
When i am writing the test using recordTest() the following code appears in relation to the fileInput control:
app$uploadFile(`import_initial_data_screen/file_input` = c("COS_.xlsx","PDS_.xlsx","SPS_.xlsx","SSW_.xlsx")) # <-- This should be the path to the file, relative to the app's tests/ directory

I copied 4 files into /tests folder so that they can be picked by the test, but as soon as the test gets to the line, the following error message is displayed:

Error in session_makeRequest(self, private, endpoint, data, params, headers) : 
  SyntaxError: DOM Exception 12

Any help on how to get around it would be much appreciated!
Thanks

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
