### ISSUE TITLE
The inequality sign in the console "differences detected" message appears as "<U+2260>"

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#77]
Windows 7, RStudio 1.1.39, shinytest 1.0.2

```
    Name               Status      
    001.json  <U+2260> Files differ
```

**Comment by wch** [comment]
It looks like this is because `print.data.frame` calls `format` on each column, and this is what happens in Windows:

```
> format("\U2260")
[1] "<U+2260>"
```

This happens even though you can `print` the character just fine in Windows:

```
> print("\U2260")
[1] "≠"
```

I think this happens because the character isn't present in the default encoding for Windows.

So we'll have to use a different character or figure out how to make format not escape it.
